# Foundations Summary

Synthesize verified findings from the foundations labs without introducing unmeasured claims.

## Objectives

Connect CPU, memory, CUDA, profiling, and RDMA observations and identify the next experiments they justify.

## Background

System performance emerges from interactions among compute, memory, storage, scheduling, accelerator execution, and communication.

## Prediction

The completed foundations labs will not support a single universal performance bottleneck. Instead, the dominant constraint should depend on workload scale and execution phase:

- small CPU workloads will be sensitive to core selection, affinity, interpreter overhead, and cache locality;
- sufficiently large CPU and GPU workloads will increasingly expose memory bandwidth and access-pattern effects;
- small CUDA operations will be disproportionately affected by launch and synchronization overhead;
- independent GPU work may overlap only when resource use and dependencies leave concurrency available;
- profiling should show that host-side, device-side, and synchronization time must be measured separately;
- communication between two DGX Spark systems will remain much slower than local memory movement, making communication volume and synchronization frequency important for distributed LLM workloads.

Before treating any of these expectations as findings, this notebook will verify which preceding notebooks contain executed measurements and completed interpretations on the current `main` branch.

## Environment

In [ ]:
import os
import platform
import socket
import sys
from pathlib import Path

repository_root = next(
    (
        path
        for path in (Path.cwd(), *Path.cwd().parents)
        if (path / "pyproject.toml").is_file()
    ),
    None,
)
if repository_root is None:
    raise RuntimeError("Run this notebook from within the repository")
if str(repository_root) not in sys.path:
    sys.path.insert(0, str(repository_root))

print(f"Python: {sys.version}")
print(f"Platform: {platform.platform()}")
print(f"Hostname: {socket.gethostname()}")
print(f"Working directory: {os.getcwd()}")

## Experiment

In [ ]:
import json
from pathlib import Path

import pandas as pd


foundations_directory = repository_root / "experiments" / "00-foundations"

source_notebooks = sorted(
    path
    for path in foundations_directory.glob("[0-9][0-9]-*.ipynb")
    if path.name != "10-summary.ipynb"
)

expected_prefixes = [f"{index:02d}" for index in range(10)]
actual_prefixes = [path.name.split("-", maxsplit=1)[0] for path in source_notebooks]

if actual_prefixes != expected_prefixes:
    raise RuntimeError(
        "Expected foundations notebooks 00 through 09, "
        f"but found prefixes {actual_prefixes}"
    )


def cell_source(cell: dict[str, object]) -> str:
    return "".join(cell.get("source", []))


def output_contains_error(cell: dict[str, object]) -> bool:
    return any(
        output.get("output_type") == "error" for output in cell.get("outputs", [])
    )


def section_body(
    cells: list[dict[str, object]],
    heading: str,
) -> str | None:
    lines: list[str] = []
    collecting = False

    for cell in cells:
        if cell.get("cell_type") != "markdown":
            continue

        text = cell_source(cell).strip()
        if not text:
            continue

        cell_lines = text.splitlines()
        first_line = cell_lines[0].strip()

        if collecting and first_line.startswith("## "):
            break

        if first_line == heading:
            collecting = True
            lines.extend(cell_lines[1:])
        elif collecting:
            lines.extend(cell_lines)

    body = "\n".join(lines).strip()
    return body or None


section_names = [
    "Prediction",
    "Observations",
    "Explanation",
    "Connection to LLMs",
    "Further Exploration",
]

notebook_records: list[dict[str, object]] = []
section_records: list[dict[str, object]] = []
loaded_notebooks: dict[str, dict[str, object]] = {}

for notebook_path in source_notebooks:
    notebook = json.loads(notebook_path.read_text())
    loaded_notebooks[notebook_path.name] = notebook

    cells = notebook["cells"]
    code_cells = [cell for cell in cells if cell.get("cell_type") == "code"]
    markdown_cells = [cell for cell in cells if cell.get("cell_type") == "markdown"]

    executed_code_cells = [
        cell
        for cell in code_cells
        if cell.get("execution_count") is not None or bool(cell.get("outputs"))
    ]

    error_cells = [cell for cell in code_cells if output_contains_error(cell)]

    notebook_source = "\n".join(cell_source(cell) for cell in cells)

    extracted_sections = {
        section_name: section_body(
            cells,
            f"## {section_name}",
        )
        for section_name in section_names
    }

    observations = extracted_sections["Observations"]
    explanation = extracted_sections["Explanation"]

    observations_complete = observations is not None and "TODO" not in observations
    explanation_complete = explanation is not None and "TODO" not in explanation

    notebook_records.append(
        {
            "notebook": notebook_path.name,
            "markdown_cells": len(markdown_cells),
            "code_cells": len(code_cells),
            "executed_code_cells": len(executed_code_cells),
            "execution_coverage": (
                len(executed_code_cells) / len(code_cells) if code_cells else None
            ),
            "saved_error_cells": len(error_cells),
            "todo_occurrences": notebook_source.count("TODO"),
            "observations_complete": observations_complete,
            "explanation_complete": explanation_complete,
            "summary_candidate": (observations_complete and explanation_complete),
        }
    )

    for section_name, body in extracted_sections.items():
        section_records.append(
            {
                "notebook": notebook_path.name,
                "section": section_name,
                "present": body is not None,
                "complete": (body is not None and "TODO" not in body),
                "character_count": (len(body) if body is not None else 0),
                "body": body,
            }
        )


notebook_inventory = pd.DataFrame(notebook_records)
recorded_sections = pd.DataFrame(section_records)

notebook_inventory

,notebook,markdown_cells,code_cells,executed_code_cells,execution_coverage,saved_error_cells,todo_occurrences,observations_complete,explanation_complete,summary_candidate
0,00-machine-overview.ipynb,10,2,2,1.000000,0,1,True,True,True
1,01-cpu-architecture.ipynb,10,2,2,1.000000,0,2,True,True,True
2,02-memory-hierarchy.ipynb,10,28,28,1.000000,0,1,True,True,True
3,03-linux-memory.ipynb,10,28,27,0.964286,0,1,True,True,True
4,04-vectorization.ipynb,10,17,17,1.000000,0,1,True,True,True
5,05-cuda-fundamentals.ipynb,18,22,22,1.000000,0,0,True,True,True
6,06-gpu-memory.ipynb,15,18,15,0.833333,0,1,True,True,True
7,07-cuda-streams.ipynb,14,19,17,0.894737,0,0,True,True,True
8,08-profiling.ipynb,27,40,39,0.975000,0,0,True,True,True
9,09-rdma-fundamentals.ipynb,25,69,63,0.913043,0,0,True,True,True

In [ ]:
inventory_summary = pd.Series(
    {
        "source_notebooks": len(notebook_inventory),
        "notebooks_with_saved_outputs": int(
            (notebook_inventory["executed_code_cells"] > 0).sum()
        ),
        "notebooks_with_saved_errors": int(
            (notebook_inventory["saved_error_cells"] > 0).sum()
        ),
        "notebooks_containing_todos": int(
            (notebook_inventory["todo_occurrences"] > 0).sum()
        ),
        "completed_observation_sections": int(
            notebook_inventory["observations_complete"].sum()
        ),
        "completed_explanation_sections": int(
            notebook_inventory["explanation_complete"].sum()
        ),
        "summary_candidates": int(notebook_inventory["summary_candidate"].sum()),
    },
    name="count",
)

inventory_summary.to_frame()

                                count
source_notebooks                   10
notebooks_with_saved_outputs       10
notebooks_with_saved_errors         0
notebooks_containing_todos          6
completed_observation_sections     10
completed_explanation_sections     10
summary_candidates                 10

In [ ]:
section_status = (
    recorded_sections.pivot(
        index="notebook",
        columns="section",
        values="complete",
    )
    .rename_axis(columns=None)
    .reset_index()
)

for section_name in section_names:
    if section_name in section_status:
        section_status[section_name] = section_status[section_name].map(
            {
                True: "complete",
                False: "TODO or missing",
            }
        )

section_status

,notebook,Connection to LLMs,Explanation,Further Exploration,Observations,Prediction
0,00-machine-overview.ipynb,complete,complete,complete,complete,TODO or missing
1,01-cpu-architecture.ipynb,complete,complete,complete,complete,TODO or missing
2,02-memory-hierarchy.ipynb,complete,complete,TODO or missing,complete,complete
3,03-linux-memory.ipynb,complete,complete,TODO or missing,complete,complete
4,04-vectorization.ipynb,complete,complete,TODO or missing,complete,complete
5,05-cuda-fundamentals.ipynb,complete,complete,complete,complete,complete
6,06-gpu-memory.ipynb,complete,complete,TODO or missing,complete,complete
7,07-cuda-streams.ipynb,complete,complete,complete,complete,complete
8,08-profiling.ipynb,complete,complete,complete,complete,complete
9,09-rdma-fundamentals.ipynb,complete,complete,complete,complete,complete

### Evidence-admission criterion

Notebook completion is not inferred from execution-count coverage alone. A notebook is admitted as a summary candidate when:

- its Observations section contains completed prose;
- its Explanation section contains completed prose;
- neither section is still marked as TODO.

This admits the notebook's narrative as a candidate index. It does not automatically validate every claim in that prose. Numerical statements must still be traceable to saved outputs, while causal explanations must remain distinguishable from measurements.

In [ ]:
candidate_notebooks = notebook_inventory.loc[
    notebook_inventory["summary_candidate"],
    "notebook",
].tolist()

excluded_notebooks = notebook_inventory.loc[
    ~notebook_inventory["summary_candidate"],
    [
        "notebook",
        "observations_complete",
        "explanation_complete",
    ],
].reset_index(drop=True)

print(f"Summary candidates: {len(candidate_notebooks)} / {len(notebook_inventory)}")

for notebook in candidate_notebooks:
    print(f"- included: {notebook}")

for row in excluded_notebooks.itertuples(index=False):
    missing_sections = []

    if not row.observations_complete:
        missing_sections.append("Observations")
    if not row.explanation_complete:
        missing_sections.append("Explanation")

    print(f"- excluded: {row.notebook} ({', '.join(missing_sections)} incomplete)")

Summary candidates: 10 / 10
- included: 00-machine-overview.ipynb
- included: 01-cpu-architecture.ipynb
- included: 02-memory-hierarchy.ipynb
- included: 03-linux-memory.ipynb
- included: 04-vectorization.ipynb
- included: 05-cuda-fundamentals.ipynb
- included: 06-gpu-memory.ipynb
- included: 07-cuda-streams.ipynb
- included: 08-profiling.ipynb
- included: 09-rdma-fundamentals.ipynb

In [ ]:
candidate_narrative = (
    recorded_sections[
        recorded_sections["notebook"].isin(candidate_notebooks)
        & recorded_sections["section"].isin(
            [
                "Observations",
                "Explanation",
                "Connection to LLMs",
                "Further Exploration",
            ]
        )
        & recorded_sections["complete"]
    ]
    .copy()
    .sort_values(
        [
            "notebook",
            "section",
        ]
    )
    .reset_index(drop=True)
)

candidate_narrative[
    [
        "notebook",
        "section",
        "character_count",
        "body",
    ]
]

,notebook,section,character_count,body
0,00-machine-overview.ipynb,Connection to LLMs,676,The shared memory capacity sets an upper bound...
1,00-machine-overview.ipynb,Explanation,608,"The results confirm the expected architecture,..."
2,00-machine-overview.ipynb,Further Exploration,231,Map each logical CPU number to its core model ...
3,00-machine-overview.ipynb,Observations,831,- The machine runs 64-bit `aarch64` Linux with...
4,01-cpu-architecture.ipynb,Connection to LLMs,487,"SVE, BF16, and 8-bit matrix instructions can a..."
5,01-cpu-architecture.ipynb,Explanation,536,The matching identifiers show that logical CPU...
6,01-cpu-architecture.ipynb,Further Exploration,305,Read the `CPU part` value for every logical CP...
7,01-cpu-architecture.ipynb,Observations,475,- The saved output shows complete records for ...
8,02-memory-hierarchy.ipynb,Connection to LLMs,110,Memory hierarchy behavior influences embedding...
9,02-memory-hierarchy.ipynb,Explanation,1143,Cache capacity is not a hard threshold at whic...
10,02-memory-hierarchy.ipynb,Observations,1749,The DGX Spark CPU exhibits distinct latency re...
11,03-linux-memory.ipynb,Connection to LLMs,732,LLM runtimes often load model weights through ...
12,03-linux-memory.ipynb,Explanation,2886,Linux separates virtual address-space reservat...
13,03-linux-memory.ipynb,Observations,2132,Reserving a 1 GiB anonymous mapping increased ...
14,04-vectorization.ipynb,Connection to LLMs,101,Vectorization underpins optimized preprocessin...
15,04-vectorization.ipynb,Explanation,1438,The scalar and vectorized C implementations re...
16,04-vectorization.ipynb,Observations,1484,Python was faster for the smallest 16-element ...
17,05-cuda-fundamentals.ipynb,Connection to LLMs,1845,LLM inference and training consist of many CUD...
18,05-cuda-fundamentals.ipynb,Explanation,3195,The experiments distinguish several separate c...
19,05-cuda-fundamentals.ipynb,Further Exploration,594,Possible follow-up experiments include:\n\n- m...
20,05-cuda-fundamentals.ipynb,Observations,2110,The environment exposed one NVIDIA GB10 device...
21,06-gpu-memory.ipynb,Connection to LLMs,94,"Weights, activations, and KV caches place sust..."
22,06-gpu-memory.ipynb,Explanation,5442,### Measured conclusions\n\nPyTorch distinguis...
23,06-gpu-memory.ipynb,Observations,3917,The CUDA runtime exposed one NVIDIA GB10 devic...
24,07-cuda-streams.ipynb,Connection to LLMs,1242,LLM inference systems use CUDA streams to coor...
25,07-cuda-streams.ipynb,Explanation,1960,A CUDA stream is an ordered queue. Operations ...
26,07-cuda-streams.ipynb,Further Exploration,697,Potential extensions include:\n\n- capture the...
27,07-cuda-streams.ipynb,Observations,2233,### Host submission versus completion\n\nFor 3...
28,08-profiling.ipynb,Connection to LLMs,1616,"LLM systems combine several execution layers, ..."
29,08-profiling.ipynb,Explanation,1988,The prediction that transformation would domin...
30,08-profiling.ipynb,Further Exploration,848,Possible extensions include:\n\n- vectorize th...
31,08-profiling.ipynb,Observations,1965,The controlled workload was deterministic and ...
32,09-rdma-fundamentals.ipynb,Connection to LLMs,2720,Distributed LLM workloads move large tensors b...
33,09-rdma-fundamentals.ipynb,Explanation,2971,This notebook measured the RDMA topology and b...
34,09-rdma-fundamentals.ipynb,Further Exploration,2947,This notebook measured RDMA latency and bandwi...
35,09-rdma-fundamentals.ipynb,Observations,664,Run the cells on one DGX Spark. Keep all outpu...

In [ ]:
from IPython.display import Markdown, display


for notebook in candidate_notebooks:
    display(Markdown(f"### `{notebook}`"))

    notebook_sections = candidate_narrative[candidate_narrative["notebook"] == notebook]

    for row in notebook_sections.itertuples(index=False):
        display(Markdown(f"#### {row.section}\n\n{row.body}"))

### `00-machine-overview.ipynb`

#### Connection to LLMs

The shared memory capacity sets an upper bound for model weights, the key-value cache, activations, and host processes.

The GB10 GPU performs the matrix operations used for token generation. The CPU cores support tokenization, scheduling, and data preparation.

The heterogeneous CPU cores can produce variable preprocessing performance when the operating system moves work between core types.

The NVMe device affects model load time and weight transfer after a model leaves memory. ConnectX-7 can support communication between nodes.

This overview does not measure bandwidth, latency, or token throughput. Later experiments must measure these values under an LLM workload.

#### Explanation

The results confirm the expected architecture, core count, CPU models, NUMA layout, GPU, network adapter, and NVMe storage.

The two CPU model entries describe the heterogeneous core groups. Each entry accounts for 10 of the 20 physical cores.

The expected 128 GB and reported 121 GiB use different units. Platform reservations can also reduce memory visible to Linux.

`nvidia-smi` reports `Not Supported` for GPU memory use. The output therefore does not measure the GB10 unified memory pool.

The PCIe output confirms ConnectX-7 hardware but does not show link speed, link width, or active network ports.

#### Further Exploration

Map each logical CPU number to its core model and maximum frequency through `/sys/devices/system/cpu`.

Then pin the same preprocessing task to each core group with `taskset`. Compare runtime and confirm the performance difference.

#### Observations

- The machine runs 64-bit `aarch64` Linux with kernel `6.17.0-1026-nvidia`.
- The CPU has 20 online cores and one thread per core.
- Ten Cortex-X925 cores reach 3.9 GHz. Ten Cortex-A725 cores reach 2.808 GHz.
- One NUMA node contains all 20 CPU cores and 124,609 MB of memory.
- `free -h` reports 121 GiB total memory, 114 GiB available memory, and 15 GiB swap.
- `nvidia-smi` identifies one NVIDIA GB10 GPU with driver 580.159.03 and CUDA 13.0 support.
- The idle GPU used 4 W, had 0% utilization, and had a temperature of 47 degrees Celsius.
- A 3.7 TB Samsung NVMe device contains the EFI and root partitions.
- PCIe lists four ConnectX-7 Ethernet functions, one Realtek Ethernet controller, and one MediaTek network controller.
- All seven commands completed successfully. No command timed out or reported a missing executable.

### `01-cpu-architecture.ipynb`

#### Connection to LLMs

SVE, BF16, and 8-bit matrix instructions can accelerate compatible CPU kernels used in preprocessing and model inference.

CPU performance also affects tokenization, request scheduling, sampling, and data transfer to the GPU.

A scheduler can move these tasks between different core types. That movement can change latency and reduce benchmark repeatability.

This run confirms instruction support for only the displayed CPUs. It does not measure any effect on LLM latency or throughput.

#### Explanation

The matching identifiers show that logical CPUs 0 and 1 use the same ARM core part. The truncated sample cannot describe all cores.

The feature flags describe supported instructions. They do not measure instruction speed or identify the faster and slower core groups.

BogoMIPS is a kernel calibration value, not a performance benchmark. Equal BogoMIPS values do not prove equal core performance.

The experiment does not set CPU affinity or run a timed workload. It therefore cannot show scheduler effects or compare core performance.

#### Further Exploration

Read the `CPU part` value for every logical CPU from `/proc/cpuinfo`. Group the logical CPUs by that value.

Use `taskset` to pin one deterministic, single-threaded workload to one CPU from each group.

Run each case many times and alternate the test order. Report the median time and the observed spread.

#### Observations

- The saved output shows complete records for logical CPUs 0 and 1.
- Both records report ARM implementer `0x41`, architecture version 8, part `0xd87`, revision 1, and 2000.00 BogoMIPS.
- Both logical CPUs report the same feature set, including SVE, SVE2, BF16, and 8-bit matrix multiplication.
- The 1,000-character output ends inside the record for logical CPU 2.
- The run reports no core model names, CPU count, affinity settings, workload timings, or scheduler activity.

### `02-memory-hierarchy.ipynb`

#### Connection to LLMs

Memory hierarchy behavior influences embedding lookup, preprocessing, CPU kernels, and movement of model data.

#### Explanation

Cache capacity is not a hard threshold at which every access suddenly becomes a main-memory access. When a randomized working set exceeds cache capacity, some lines may remain resident while others miss, producing an average latency between pure cache-hit and DRAM latency. Set associativity, replacement policy, address hashing, page translation, and physical-memory placement can also make similarly sized working sets behave differently. The larger L3 domain nevertheless provides a repeatable latency advantage over a broad range of larger working sets.

The original sequential benchmark was constrained by a loop-carried dependency through one accumulator, limiting useful throughput to approximately one 64-bit element per CPU cycle. Eight independent accumulators allowed the compiler to use SIMD and overlap multiple load and addition operations. Once this execution bottleneck was removed, the memory hierarchy became visible. Private-cache-resident arrays sustained approximately 124–125 GB/s, shared-L3-resident arrays sustained approximately 98–108 GB/s, and large DRAM-resident arrays sustained approximately 32–35 GB/s per core.

#### Observations

The DGX Spark CPU exhibits distinct latency regimes corresponding broadly to private cache, shared cache, and main memory. Dependent-load latency rises from approximately 1.3 ns for small L1-resident working sets to approximately 4 ns in the L2 region, approximately 6 ns in the shared-cache region, and tens to roughly 100 ns for large working sets.

The fixed-layout focused sweep substantially reduced repetition-level variability. The CPU attached to the 16 MiB L3 domain generally exhibited lower dependent-load latency than the CPU attached to the 8 MiB domain, particularly for working sets above approximately 16 MiB. The transition from shared-cache to main-memory behavior was gradual and non-monotonic rather than a sharp boundary at the reported cache capacities. Some working-set sizes, notably 32 MiB, produced unexpectedly low latency on both CPUs, indicating sensitivity to address layout, cache indexing, TLB behavior, or physical-memory mapping.

A single X925 core sustains approximately 31 GB/s while performing a sequential 64-bit summation over cache-resident arrays and approximately 29 GB/s over large DRAM-resident arrays.

After replacing the single reduction dependency with eight independent accumulators, GCC vectorized the main sequential-read loop using 128-bit vectors. Cache-resident bandwidth increased from approximately 31 GB/s to approximately 124–125 GB/s. Throughput remained nearly constant between the 32 KiB and 1 MiB working sets, fell to approximately 98–108 GB/s at 4 MiB, and declined to approximately 32–35 GB/s for a 256 MiB DRAM-resident working set. The second X925 representative, CPU 15, consistently achieved higher bandwidth than CPU 5, particularly for shared-cache and DRAM-sized working sets.

### `03-linux-memory.ipynb`

#### Connection to LLMs

LLM runtimes often load model weights through memory-mapped files. A model file can therefore contribute to a process's virtual size before its pages are resident, and accessed weights may appear as file-backed RSS and filesystem cache rather than anonymous memory.

This distinction matters when interpreting model-server memory usage. A large RSS value composed of clean file-backed pages may be substantially more reclaimable than an equally large anonymous allocation used for activations, KV cache, or runtime workspaces. On DGX Spark, CPU and GPU share the system memory pool, so reclaimable page cache, anonymous host allocations, pinned memory, and accelerator allocations all influence the capacity available for inference.

#### Explanation

Linux separates virtual address-space reservation from physical page allocation. Creating the anonymous mapping established a valid one-GiB virtual address range, which appeared immediately in `VmSize`. The kernel did not initially allocate physical backing pages, so process RSS and anonymous RSS remained unchanged.

The first write to each page generated a page fault. Linux responded by allocating a physical page, installing the corresponding page-table entry, and marking the page private and dirty. Touching one byte per page was sufficient to make the entire page resident, which explains why RSS increased in exact 128 MiB steps even though only one byte was explicitly written in each 4 KiB page.

The process-local counters tracked the experiment precisely. System-wide counters such as `MemAvailable` and `AnonPages` showed the same general trend but also reflected unrelated process activity, kernel memory management, and cache reclamation.

Because the notebook used the Linux `fork` start method, the child initially shared many inherited Python pages with the notebook process through copy-on-write. Normal child-process execution dirtied some of those inherited pages, explaining the small additional increase in `Private_Dirty` that remained after the experimental mapping had been released.

A file-backed mapping, like an anonymous mapping, initially reserves only virtual address space. Physical pages become resident on first access through demand paging. The difference is the source and accounting of those pages.

Pages faulted from the regular file were counted as file-backed RSS rather than anonymous RSS. Because the mapping was read-only, the pages remained clean: their contents still matched the backing file and could be discarded without first writing them to storage. The pages appeared as private clean in `smaps` because only the experimental process was currently mapping them; this classification is distinct from whether the mapping was created with `MAP_SHARED`.

Reading the file also populated the Linux page cache. The same physical pages therefore served both as the process's resident file-backed pages and as cached filesystem data. This does not imply that the memory was counted twice physically; the counters describe different relationships to the same pages.

Unmapping removed the pages from the process's virtual address space and resident set, but did not immediately remove them from RAM. Linux retained them in the page cache so that a later read could avoid NVMe access. Because clean cache pages can be discarded and reconstructed from the file, Linux includes much of this memory when estimating `MemAvailable`.

The explicit eviction request demonstrated that process residency and system cache residency are separate. Only after the cached file pages were discarded did the system `Cached` counter fall by the full 512 MiB.

#### Observations

Reserving a 1 GiB anonymous mapping increased the child process's `VmSize` by exactly 1024 MiB, from 2634.42 MiB to 3658.42 MiB. Its RSS increased by only 0.19 MiB, while `RssAnon` and `smaps` anonymous memory did not increase. Reserving virtual address space therefore did not make the mapped pages physically resident.

Touching one byte in each 4 KiB page caused RSS and anonymous RSS to grow linearly. Each additional 128 MiB touched produced an approximately 128 MiB increase in both counters. After all 1 GiB had been touched, RSS had increased by 1024.19 MiB and anonymous RSS by exactly 1024 MiB.

The system page-table counter increased by approximately 2.1 MiB while the mapping was resident. This closely matches the roughly 2 MiB of page-table entries required to describe 262,144 individual 4 KiB pages.

Closing the mapping returned `VmSize`, RSS, and anonymous RSS to approximately their baseline values. System-wide `MemAvailable` also recovered, although its values were noisier because they included concurrent activity from the rest of the machine.


Reserving a 512 MiB file-backed mapping increased the child process's `VmSize` by exactly 512 MiB, while RSS increased by only 0.125 MiB. `RssAnon` did not change. Creating the mapping therefore established virtual address space without loading the file's pages into physical memory.

Reading one byte from each page caused process RSS and `RssFile` to grow linearly in 64 MiB increments. After the entire file had been read, both counters had increased by approximately 512 MiB. `smaps` reported exactly 512 MiB of additional private clean memory, while anonymous RSS remained unchanged.

The system `Cached` counter increased by approximately the same amount as the file data read. After unmapping the file, the process's virtual size, RSS, file-backed RSS, and private clean memory returned to baseline, but the system cache remained approximately 512 MiB higher. The pages had left the process working set but remained resident as filesystem cache.

Requesting cache eviction with `POSIX_FADV_DONTNEED` reduced the system `Cached` counter by exactly 512 MiB.

### `04-vectorization.ipynb`

#### Connection to LLMs

Vectorization underpins optimized preprocessing and many tensor operations used around LLM inference.

#### Explanation

The scalar and vectorized C implementations removed Python interpreter overhead from the comparison. The remaining difference therefore resulted primarily from compiler-generated SIMD execution and its interaction with the memory hierarchy.

The compiler used 128-bit vectors, allowing each vector instruction to process two `double` elements. For cache-resident arrays, the measured speedup approached the corresponding theoretical twofold arithmetic-width advantage. The result remained below exactly 2× because loads, stores, loop control, alignment handling, and scalar remainder processing were still required.

For very small arrays, the fixed cost of crossing the Python-to-C boundary and entering the native loop was comparable to the useful work, obscuring the SIMD benefit.

For large arrays, both kernels became constrained by data movement rather than floating-point execution. Each result required reading eight bytes and writing eight bytes. Once memory bandwidth became the limiting resource, scalar and vectorized loops transferred the same number of bytes and therefore converged in performance.

The NumPy comparison also demonstrated that “vectorized Python” combines several distinct optimizations. NumPy removes interpreter overhead and may use SIMD, but separate ufunc expressions can still require multiple passes over memory. A fused compiled kernel can outperform NumPy by combining operations into one traversal.

#### Observations

Python was faster for the smallest 16-element input because NumPy’s fixed dispatch overhead exceeded the cost of the short Python loop. NumPy overtook Python by 64 elements and reached speedups above 100× for larger arrays. The Python implementation required roughly 23–40 ns per element, whereas NumPy reached approximately 0.18–0.34 ns per element for larger inputs. Preallocating the output had little effect on small arrays but improved larger-array performance by avoiding repeated output allocation and temporary-array management.

GCC reported that the optimized C loop was vectorized using 16-byte vectors, corresponding to two `double` values per SIMD operation.

For very small arrays, native-call and loop-setup overhead dominated. At 256 elements, the vectorized implementation was slower than the scalar implementation. As the working set grew, the SIMD advantage increased. The largest speedup was 1.86× at 262,144 elements, where the scalar kernel took 70.90 µs and the vectorized kernel took 38.19 µs.

The SIMD advantage declined for larger arrays. It was 1.68× at an 8 MiB array, 1.16× at 32 MiB, and only 1.05× at 128 MiB. At the largest size, both implementations processed approximately 3.2–3.4 billion elements per second.

The fused vectorized C kernel was also substantially faster than the preallocated NumPy implementation. NumPy used two separate ufunc passes for multiplication and addition, whereas the C kernel performed both operations in one traversal.

### `05-cuda-fundamentals.ipynb`

#### Connection to LLMs

LLM inference and training consist of many CUDA operations whose performance depends on the same effects observed here.

Asynchronous launches allow the CPU to prepare and submit work while the GPU executes previously queued kernels. Unnecessary synchronization removes that overlap and can reduce throughput.

Small kernels can be dominated by fixed launch and scheduling costs. Kernel fusion and sufficiently large batches help amortize those costs.

Data locality also matters. Frequently reused model weights, activations, and intermediate values may benefit from GPU caches, while larger working sets are constrained by memory-system throughput.

Finally, cold-start costs affect model-serving latency. Loading the framework, initializing CUDA, allocating memory, and executing kernels for the first time can be much slower than steady-state inference. Production systems therefore commonly initialize and warm up models before accepting latency-sensitive requests.

CUDA Graphs are particularly relevant to autoregressive LLM inference. Each decoding step often executes a largely fixed sequence of kernels with stable tensor shapes for a given batch and sequence configuration.

Without graph capture, the CPU repeatedly submits those kernels token after token. When kernels are short, especially at small batch sizes, launch gaps can become a meaningful fraction of token latency.

Capturing the decoding step can replace many recurring Python and CUDA-runtime submissions with one graph replay. The measured 64-operation experiment illustrates both expected benefits: much lower host overhead and fewer gaps on the device timeline.

Practical LLM servers may maintain multiple captured graphs for different batch sizes or sequence-shape buckets because one captured graph cannot freely accommodate arbitrary shapes and memory addresses.

#### Explanation

The experiments distinguish several separate costs that can otherwise be conflated in CUDA benchmarks.

CUDA execution is asynchronous. The host can submit an operation and regain control after only a few microseconds while the GPU continues executing. Completion-aware timing therefore requires synchronization or CUDA events.

Host submission cost is largely independent of tensor size. Device execution, however, depends on operation size and data locality.

Small operations encounter an approximately 8 µs execution floor in this PyTorch and CUDA environment. This floor includes fixed dispatch, scheduling, event, and minimum-execution costs that the experiment does not separate.

Intermediate-size tensors can execute much faster when the same input and output regions are reused. Rotating through a much larger allocation removes most of this advantage. The result is consistent with cache residency, although the experiment does not identify a cache level or measure cache capacity directly.

For sufficiently large or rotating working sets, the multiplication approaches approximately 200–210 GiB/s of derived logical throughput. This is based on one four-byte input read and one four-byte output write per element and is not a direct measurement of physical LPDDR5X traffic.

Fresh-process measurements reveal additional one-time costs. Importing PyTorch took approximately 0.52 seconds, while the first CUDA allocation and synchronization took approximately 0.21 seconds. The first multiplication was about ten times slower than warmed-up execution.

These first-use timings aggregate several possible initialization mechanisms, including CUDA context creation, allocator setup, runtime initialization, module or kernel loading, and cache warm-up. The experiment measures their combined effect but does not attribute time to individual mechanisms.

CUDA Graph replay reduces recurring submission overhead for workloads whose operation topology, tensor shapes, and memory addresses remain fixed.

In eager execution, Python invokes every PyTorch operation separately. The measured host enqueue time therefore grows nearly linearly with the number of operations, at roughly three microseconds per addition in this experiment.

Once captured, the graph replays the complete operation sequence through one host call. Replay enqueue time remained near two microseconds whether the graph contained one operation or 64 operations.

The host-submission improvement was much larger than the completed-execution improvement. A graph replay still executes all captured GPU kernels, so it does not eliminate their arithmetic or memory work.

Completed execution nevertheless improved by up to approximately 2×. The small kernels are short enough that Python-driven submission can leave gaps between successive launches. Graph replay makes the complete sequence available to the CUDA runtime at once, reducing these inter-kernel bubbles.

CUDA Graphs therefore benefit workloads that combine stable execution structure with many short CUDA operations. Their principal trade-off is reduced dynamism: captured shapes, memory addresses, and operation topology must remain compatible across replays.

#### Further Exploration

Possible follow-up experiments include:

- measure multiple queued operations before one synchronization to demonstrate batching of host submissions;
- compare separate elementwise operations with a fused implementation;
- inspect kernel launches and memory activity with Nsight Systems or Nsight Compute;
- compare FP32, FP16, BF16, and larger element types;
- measure CUDA Graph replay against ordinary Python-driven launches;
- test concurrent CUDA streams and overlap between independent operations;
- compare PyTorch allocation behavior before and after the caching allocator is warmed up.

#### Observations

The environment exposed one NVIDIA GB10 device through PyTorch 2.13.0 and CUDA 13.0.

The asynchronous multiply-add experiment showed that the Python call returned after a median of 8.040 µs, while completed execution required approximately 1.22 ms. Synchronized host timing and CUDA-event timing agreed within approximately 0.40%.

For a single preallocated multiplication, host enqueue time remained approximately 3.2–3.7 µs across all tested sizes.

Repeatedly accessing the same tensor regions produced substantially faster intermediate-size results than rotating through a 512 MiB combined input/output working set. The largest rotating-to-hot difference was 4.44× for a 4 MiB tensor. At 16 MiB per tensor, hot and rotating timings differed by only 3.45%.

Large, non-hot operations approached approximately 200–210 GiB/s of derived logical read-plus-write throughput.

Across five fresh Python subprocesses:

- importing PyTorch took a median of 518.94 ms;
- the first CUDA allocation and synchronization took 205.57 ms;
- the first synchronized multiplication took 6.277 ms;
- a warmed-up synchronized multiplication took 0.600 ms.

The first multiplication was approximately 10.3–10.6 times slower than the warmed-up multiplication in every subprocess.

CUDA Graph replay was compared with ordinary Python-driven execution for fixed sequences of 1, 4, 16, and 64 small in-place additions.

Eager host enqueue time increased almost linearly with operation count:

- 1 operation: 3.456 µs;
- 4 operations: 13.160 µs;
- 16 operations: 51.608 µs;
- 64 operations: 196.937 µs.

CUDA Graph replay enqueue time remained approximately constant at 1.98–2.06 µs. The resulting host-submission speedup increased from 1.69× for one operation to 98.47× for 64 operations.

Completed CUDA-event execution also improved:

- 1 operation: 8.016 µs eager versus 6.528 µs graph;
- 4 operations: 17.568 µs versus 10.736 µs;
- 16 operations: 56.032 µs versus 31.168 µs;
- 64 operations: 247.792 µs versus 121.440 µs.

For the 64-operation sequence, CUDA Graph replay reduced completed execution time by approximately 2.04×.

### `06-gpu-memory.ipynb`

#### Connection to LLMs

Weights, activations, and KV caches place sustained pressure on memory capacity and bandwidth.

#### Explanation

### Measured conclusions

PyTorch distinguishes live tensor storage from memory retained for later reuse.

`memory_allocated()` tracked the storage owned by the live tensor. Deleting the final tensor reference released that logical allocation.

`memory_reserved()` tracked the larger pool managed by PyTorch's CUDA caching allocator. Deleting the tensor made its 512 MiB block unused, but PyTorch retained the block rather than immediately returning it to CUDA.

`torch.cuda.empty_cache()` returned that unused cached block, reducing reserved memory to zero. It was not required to release the tensor itself; the tensor had already been released when its final reference was deleted.

For this single large allocation, the allocator introduced no visible rounding or fragmentation: allocated and reserved memory were both exactly 512 MiB while the tensor was live.

### Architectural interpretation

The imperfect correspondence between PyTorch allocator statistics and `torch.cuda.mem_get_info()` indicates that CUDA-visible free memory is broader than PyTorch tensor storage. CUDA runtime state, allocator metadata, context allocations, other processes, and measurement-time variation can affect it.

The approximately 10 MiB difference between the first and final free-memory snapshots should therefore not be interpreted as a leaked PyTorch tensor. Both PyTorch allocated and reserved memory returned to zero.

This experiment used `torch.empty`, which creates tensor storage without initializing the elements. It demonstrates CUDA allocation accounting, but it does not establish that every byte was physically read from or written to LPDDR5X.

On the DGX Spark, CPU and GPU memory are physically unified, but PyTorch and CUDA still expose device allocations and allocator ownership as distinct software concepts. Physical unification does not remove the need to distinguish live tensors, cached allocator blocks, CUDA runtime allocations, and actual memory traffic.

### Allocation latency and reuse

A PyTorch CUDA allocation does not have one fixed cost.

When a suitable block was already present in PyTorch's caching allocator, creating a new 512 MiB tensor took a median of 37.02 microseconds. When the cache was cleared first, the same request took a median of 19.43 milliseconds.

This approximately 525-fold difference demonstrates the practical purpose of the caching allocator: tensor destruction and subsequent allocation can be extremely cheap when storage is retained and reused.

The experiment measures host-side `torch.empty` latency. It does not measure initialization bandwidth because no kernel wrote the tensor contents. The uncached duration may include CUDA runtime, driver, virtual-memory, and allocator work and should not be interpreted as the time required to transfer 512 MiB through LPDDR5X.

Calling `torch.cuda.empty_cache()` can therefore reduce visible reserved memory, but it also discards blocks that make later allocations inexpensive. It is a memory-management operation rather than a general performance optimization.

### Device-copy throughput regimes

The measurements reveal a stable large-transfer regime beginning at approximately 64 MiB in this experiment. Between 64 MiB and 1,024 MiB, effective logical bandwidth remained close to 223 GB/s and elapsed time scaled almost linearly with tensor size.

This supports the interpretation that these larger copies are primarily limited by sustained movement of source and destination data rather than fixed launch overhead.

The metric counts two logical bytes of traffic for each byte of tensor storage: one source read and one destination write. It is therefore an effective copy-bandwidth metric, not a direct measurement of raw LPDDR5X bus bandwidth.

The 1, 4, and 16 MiB results do not form a simple launch-overhead curve. In particular, the 4 MiB result of approximately 838 GB/s cannot represent sustained external-memory traffic on the same basis as the larger copies.

A likely architectural explanation is cache reuse. The experiment repeatedly copies the same initialized source and destination buffers after warm-up. Smaller working sets may be served substantially from GPU cache rather than LPDDR5X. CUDA-event resolution and fixed timing costs may also have a greater relative effect when operations take only a few microseconds.

This cache interpretation remains an inference. The current experiment measures elapsed CUDA-stream time but does not identify which cache level or physical memory supplied each access.

### Empirical cache-sensitive working-set range

The dense sweep confirms that the exceptional small-copy results form a reproducible cache-sensitive region rather than an isolated timing artifact.

Repeated copies reached approximately 890 GB/s when the source and destination together occupied 12 MiB. Effective bandwidth then declined sharply as the combined working set increased beyond 16 MiB.

By a 96 MiB combined working set, performance had converged to approximately 220 GB/s, consistent with the sustained-memory regime observed in the earlier large-copy experiment.

The result identifies an empirical transition around a 16–24 MiB combined working set for this operation. It does not directly measure the capacity of one hardware cache. Source reads, destination writes, dirty-line handling, replacement policy, copy-kernel implementation, and other cache users can all shift the observed transition.

#### Observations

The CUDA runtime exposed one NVIDIA GB10 device with 121.689 GiB of CUDA-visible memory.

A `torch.float32` tensor with 134,217,728 elements required exactly 512 MiB of logical tensor storage.

The allocator snapshots were:

| Stage | Allocated MiB | Reserved MiB | Allocator slack MiB | CUDA-visible free MiB |
|---|---:|---:|---:|---:|
| Baseline after `empty_cache()` | 0 | 0 | 0 | 98,941.73 |
| 512 MiB tensor live | 512 | 512 | 0 | 98,417.00 |
| Tensor deleted; cache retained | 0 | 512 | 512 | 98,419.47 |
| After final `empty_cache()` | 0 | 0 | 0 | 98,931.35 |

While the tensor was live, both allocated and reserved memory increased by exactly 512 MiB.

After deleting the tensor and running garbage collection, allocated memory returned to zero while all 512 MiB remained reserved by the caching allocator.

After calling `torch.cuda.empty_cache()`, reserved memory also returned to zero.

CUDA-visible free memory did not change in exact correspondence with the PyTorch allocator values. It fell by approximately 524.73 MiB when the tensor was created and ended approximately 10.38 MiB below the initial snapshot after the cache was emptied.

### Cached allocation reuse

Thirty 512 MiB allocations were measured under two conditions.

| Condition | Minimum µs | Median µs | Mean µs | Maximum µs | Standard deviation µs |
|---|---:|---:|---:|---:|---:|
| Cache cleared before allocation | 19,160.15 | 19,428.73 | 19,466.93 | 20,231.79 | 205.65 |
| Same-size cached block available | 32.40 | 37.02 | 36.98 | 41.42 | 2.30 |

The median cached allocation was approximately 525 times faster than the median allocation performed after clearing the cache.

The timing ranges did not overlap. Every cached allocation was substantially faster than every uncached allocation in this run.

Both cases produced 512 MiB of allocated memory and 512 MiB of reserved memory while the tensor was live.

### Device tensor-copy bandwidth

CUDA event timing was used to measure 50 copies at each tensor size after ten warm-up copies.

Effective bandwidth counts one logical source read and one logical destination write, for a total of twice the tensor size.

| Tensor size MiB | Median elapsed ms | Median effective bandwidth GB/s |
|---:|---:|---:|
| 1 | 0.008 | 261.622 |
| 4 | 0.010 | 837.529 |
| 16 | 0.108 | 310.505 |
| 64 | 0.598 | 224.450 |
| 256 | 2.424 | 221.452 |
| 512 | 4.830 | 222.328 |
| 1,024 | 9.484 | 226.423 |

From 64 MiB through 1,024 MiB, median effective bandwidth remained between 221.452 and 226.423 GB/s.

Elapsed time scaled approximately in proportion to tensor size across that range. Doubling the tensor from 512 MiB to 1,024 MiB increased median elapsed time from 4.830 to 9.484 ms.

The small-copy results were not monotonic. The 4 MiB copy reported 837.529 GB/s, substantially above both smaller and larger sizes. It therefore does not belong to the stable large-transfer regime.

### Repeated-copy working-set transition

A denser sweep measured repeated copies with combined source-plus-destination working sets from 2 to 256 MiB.

| Tensor size MiB | Combined working set MiB | Median elapsed µs | Median effective bandwidth GB/s |
|---:|---:|---:|---:|
| 1 | 2 | 7.744 | 270.810 |
| 2 | 4 | 8.128 | 516.031 |
| 4 | 8 | 10.016 | 837.521 |
| 6 | 12 | 14.144 | 889.629 |
| 8 | 16 | 23.296 | 720.176 |
| 12 | 24 | 70.752 | 355.691 |
| 16 | 32 | 115.104 | 291.514 |
| 24 | 48 | 202.176 | 248.950 |
| 32 | 64 | 286.080 | 234.581 |
| 48 | 96 | 459.280 | 219.176 |
| 64 | 128 | 612.752 | 219.041 |
| 96 | 192 | 909.744 | 221.300 |
| 128 | 256 | 1,208.736 | 222.079 |

Effective bandwidth peaked at 889.629 GB/s for a 12 MiB combined working set.

The largest decline occurred between combined working sets of 16 and 24 MiB, where median bandwidth fell from 720.176 to 355.691 GB/s.

At combined working sets of 96 MiB and larger, median bandwidth stabilized between approximately 219 and 222 GB/s.

### `07-cuda-streams.ipynb`

#### Connection to LLMs

LLM inference systems use CUDA streams to coordinate work with different dependency structures, including:

- model execution for separate requests;
- asynchronous memory copies;
- collective communication;
- attention and expert-routing work;
- preprocessing and postprocessing kernels;
- pipeline stages across devices.

Streams are most useful when workloads are independent and leave complementary or unused device resources. Running two already-saturating matrix multiplications in separate streams does not double throughput.

Events provide device-side coordination without forcing the CPU to wait. An inference runtime can therefore express dependencies such as:

1. a transfer must complete before a kernel consumes its data;
2. communication must complete before a later model layer begins;
3. independent requests may proceed in separate streams;
4. a coordinating stream may wait for several workers before continuing.

The measured results also illustrate the difference between latency and throughput. Concurrent streams reduced aggregate makespan, but contention made each individual worker interval longer. An inference server may accept higher per-request latency when the resulting overlap improves total request throughput.

#### Explanation

A CUDA stream is an ordered queue. Operations submitted to one stream execute according to that stream's ordering rules, while submission from the host normally remains asynchronous.

The first experiment separated host submission from device completion. Python enqueued approximately 253 ms of GPU work in about 0.15 ms. The missing time appeared when the host synchronized with the completion event.

Multiple streams create separate ordering domains, but they do not create additional GPU hardware. Concurrent execution depends on whether independently schedulable workloads can share the device's finite resources.

The large `4096 × 4096` GEMMs gained little from two streams. This is consistent with each GEMM already using most of the relevant compute capacity, although the timing experiment did not directly measure occupancy.

The matrix-size sweep showed that useful overlap was workload-dependent rather than monotonic. The `2048 × 2048` case produced the largest makespan reduction. Smaller GEMMs were less efficient because equal nominal arithmetic required many more kernel launches and incurred more fixed per-operation cost.

The dependency experiment distinguished stream independence from stream concurrency. In the independent case, both streams had simultaneously active event intervals. In the dependent case, `stream_b.wait_event(stream_a_done)` prevented stream B from starting until stream A had completed.

The independent worker intervals overlapped for nearly the entire makespan, but each half-workload ran much longer under contention than it did alone. This explains why overlap improved throughput by only about 6% rather than approaching a twofold speedup.

CUDA event intervals establish stream-level timing and ordering. They do not reveal the precise kernel execution timeline, SM occupancy, or which kernel phases executed concurrently. Those questions require profiling with tools such as Nsight Systems or Nsight Compute.

#### Further Exploration

Potential extensions include:

- capture the experiments with Nsight Systems to inspect the actual kernel timeline;
- compare FP32, TF32, FP16, and BF16 GEMMs;
- test more than two streams;
- measure compute overlap with asynchronous memory operations;
- compare event dependencies with host-side synchronization;
- investigate stream priorities;
- repeat the size sweep with CUDA Graph replay to reduce Python launch overhead;
- evaluate representative LLM operations rather than isolated square GEMMs.

These extensions should preserve the distinction between:

- overlapping stream intervals;
- concurrent kernel execution;
- reduced aggregate makespan;
- improved application-level throughput.

#### Observations

### Host submission versus completion

For 32 `4096 × 4096` FP32 matrix multiplications in the default stream:

- median host enqueue time was `0.152 ms`;
- median synchronization wait was `252.753 ms`;
- median synchronized wall time was `252.913 ms`;
- median CUDA-event elapsed time was `252.899 ms`.

The final event was not complete immediately after submission in any measured trial. Python therefore returned while nearly all GPU execution remained outstanding.

CUDA-event time and synchronized wall time differed by only `0.014 ms` at the median for this long-running workload.

### One stream versus two streams

Splitting the same 32 large GEMMs equally across two independent streams changed median GPU makespan from:

- `253.910 ms` with one stream;
- to `249.625 ms` with two streams.

This was a `1.017×` speedup, or a `1.69%` makespan reduction. Separate streams therefore provided little benefit for the large-GEMM workload.

### Matrix-size sweep

Keeping nominal arithmetic work approximately constant produced:

| Matrix size | Multiplications | One stream | Two streams | Speedup |
|---:|---:|---:|---:|---:|
| 512 | 16,384 | 505.265 ms | 499.207 ms | 1.012× |
| 1024 | 2,048 | 294.349 ms | 290.899 ms | 1.012× |
| 2048 | 256 | 268.367 ms | 252.042 ms | 1.065× |
| 4096 | 32 | 255.741 ms | 251.478 ms | 1.017× |

The strongest observed two-stream benefit occurred at matrix size 2048, where makespan fell by `6.08%`.

Equal nominal FLOP counts did not produce equal execution times. The smaller-GEMM workloads required many more launches and completed less efficiently.

### Explicit cross-stream dependency

For 256 `2048 × 2048` GEMMs split equally across two streams:

- independent-stream median makespan was `252.846 ms`;
- dependency-serialized median makespan was `268.736 ms`;
- the explicit dependency added `6.28%` to makespan.

With independent streams, the recorded worker intervals overlapped for a median of `251.085 ms`.

With stream B waiting for stream A's completion event:

- stream A ended at `134.186 ms`;
- stream B started at `134.189 ms`;
- calculated interval overlap was `0.000 ms`.

The event dependency therefore serialized the stream intervals without requiring host synchronization.

### `08-profiling.ipynb`

#### Connection to LLMs

LLM systems combine several execution layers, each requiring different profiling evidence:

- Python orchestration, request handling, tokenization, scheduling, and post-processing;
- compiled CPU libraries;
- CUDA kernel launches and synchronization;
- GPU kernels;
- host-to-device, device-to-host, and inter-device transfers;
- distributed collectives;
- memory allocation and cache management.

A Python function profile can identify expensive orchestration paths, excessive calls, tokenization work, serialization, or synchronous control flow. It cannot determine whether a CUDA kernel has poor occupancy, whether tensor cores are used effectively, or whether execution is limited by device memory bandwidth.

Similarly, GPU kernel timing alone can miss Python launch overhead, request queueing, synchronization, data conversion, and communication.

The profiling workflow from this notebook generalizes to LLM workloads:

1. define the symptom and the measurement boundary;
2. establish an unprofiled end-to-end baseline;
3. choose a profiler appropriate to the suspected layer;
4. quantify profiler perturbation;
5. identify a bottleneck without over-interpreting the evidence;
6. change one relevant implementation detail;
7. validate output correctness;
8. measure end-to-end improvement;
9. profile the changed system again.

Bottleneck migration is common in inference systems. Accelerating attention kernels may expose sampling or tokenization overhead. Reducing Python launch overhead may expose memory bandwidth. Increasing single-GPU throughput may make networking or collective communication dominant.

#### Explanation

The prediction that transformation would dominate was supported by two independent measurement methods.

`cProfile` identifies expensive Python call paths. Its distinction between internal and cumulative time was important:

- `profiling_workload` had high cumulative time because it contained the complete call path;
- `transform_values` had the greatest internal time because its own body performed most of the work.

The profiler does not explain why `transform_values` was expensive at the processor level. Its output cannot distinguish Python bytecode dispatch, arbitrary-precision integer operations, allocation, cache behavior, branch behavior, or instruction throughput.

The approximately 4.3% `cProfile` slowdown is specific to this workload and profiler configuration. This workload makes only a few long-running Python function calls. A call-heavy workload could experience substantially greater deterministic-profiling overhead.

Manual phase timing produced almost the same relative attribution with much less instrumentation. However, the sequence of timing experiments showed that measurement boundaries must include semantically identical work.

In particular, an internal timestamp recorded before a function returns can omit reference-count decrements and deallocation of local objects. Releasing the transformed list of one million Python integers took approximately 5.8 ms. That work was included naturally in the externally timed function call but was initially excluded from the internal phase timer.

After matching the boundaries and interleaving trial order, the remaining manual-instrumentation effect was smaller than the observed noise. The experiment therefore supports only an upper-bound-style conclusion: manual timestamp overhead was negligible relative to a roughly 456 ms workload, not that it was zero.

The profiling evidence supports optimization of `transform_values` first. It does not yet establish which implementation change would be effective.

#### Further Exploration

Possible extensions include:

- vectorize the checksum and histogram, then re-profile the fully array-based pipeline;
- compare deterministic profiling with a statistical sampling profiler;
- run the Python workload under `perf stat` to collect cycles, instructions, branches, and cache-related counters;
- inspect the NumPy transformation with system-level sampling to determine where compiled execution occurs;
- vary workload size to separate fixed profiler cost from per-element cost;
- construct a call-heavy workload to show how deterministic-profiler overhead depends on call frequency;
- profile a CUDA workload with separate measurements for Python enqueue time, GPU execution time, and synchronized wall time;
- compare profiles before and after CUDA Graph capture;
- examine CPU–GPU synchronization points in an inference-style pipeline.

#### Observations

The controlled workload was deterministic and produced the same checksum and histogram summary on repeated executions.

The initial unprofiled baseline had a median wall time of 470.071 ms across seven trials. Its relative standard deviation was 0.155%, providing a stable reference at that point in the notebook execution.

Running the workload under `cProfile` produced a median wall time of 490.169 ms. Relative to the initial baseline, this was:

- 20.097 ms additional median runtime;
- a 1.043× slowdown;
- 4.275% apparent profiling overhead.

In the representative `cProfile` run, internal time was attributed primarily to:

- `transform_values`: 388.478 ms;
- `calculate_weighted_checksum`: 63.785 ms;
- `build_low_byte_histogram`: 28.392 ms.

`profiling_workload` itself had negligible internal time but 480.672 ms cumulative time because it called all three phases.

Independent manual phase timing reproduced the same ordering. After including result construction and local-object cleanup, the median phase distribution was:

- transformation: 354.261 ms, or 78.084%;
- checksum: 62.882 ms, or 13.860%;
- histogram: 30.704 ms, or 6.768%;
- local cleanup: 5.839 ms, or 1.287%;
- result finalization: 0.004 ms, or 0.001%.

An early comparison incorrectly suggested that manual instrumentation made the workload faster. Interleaving the configurations did not initially remove this difference because their timing boundaries were unequal: the manually timed path stopped before releasing its million-element transformed list.

After explicitly including local cleanup, the interleaved comparison produced:

- uninstrumented median: 457.637 ms;
- phase-timed median: 455.980 ms;
- median paired difference: -1.372 ms, or -0.299%;
- paired differences ranging from -1.000% to +0.520%.

Because the corrected paired differences cross zero and are small relative to runtime variation, the overhead of the manual timestamps was not resolvable in this experiment.

### `09-rdma-fundamentals.ipynb`

#### Connection to LLMs

Distributed LLM workloads move large tensors between accelerators and systems. The communication can include these operations:

- Tensor-parallel collectives
- Pipeline-parallel activation transfers
- Expert routing for mixture-of-experts models
- Gradient synchronization
- Optimizer-state or parameter transfers
- Distributed checkpoints
- Remote KV-cache access or migration

The notebook measured two communication regimes that affect these workloads.

### Small transfers and synchronization

The 8-byte test measures the fixed cost of a very small RDMA operation. LLM collectives use large buffers but also use small control transfers.

A difference of several tenths of a microsecond has little effect on one operation. It can matter across many sequential communication steps.

Latency is important for these workloads:

- Fine-grained tensor parallelism
- Small microbatches
- Pipeline bubbles
- Frequent expert-routing transfers
- Inference with short sequences or small batches

The CPU results show that host execution affects low-level communication tests. Use Cortex-X925 cores for runtime threads that launch, poll, schedule, or coordinate communication.

### Large tensor transfers

The bandwidth sweep better represents transfers of activations, parameters, gradients, or KV-cache blocks.

One PCI host path supported approximately 110 Gb/s, or 13.7 GB/s. Both paths together supported approximately 196 Gb/s, or 24.5 GB/s.

Use this simplified transfer-time estimate:

$$
t \approx \frac{\text{tensor size}}{\text{effective bandwidth}}
$$

A 1 GiB transfer takes approximately 78 ms at 13.7 GB/s. It takes approximately 44 ms at 24.5 GB/s.

These estimates exclude software overhead, collective structure, contention, and overlap with computation.

Software that uses only one RDMA interface leaves much of the available network capacity unused. An LLM runtime must use both RDMA paths.

The runtime can use one of these methods:

- Divide traffic between both paths.
- Use a transport that knows the dual-path topology.
- Create communication channels with routes across both paths.

More queue pairs on one interface do not solve this problem.

### Communication and computation overlap

LLM systems usually overlap communication with other work:

- Matrix multiplication
- Attention computation
- Expert execution
- Pipeline work between layers
- Host scheduling

Thus, the measured network rate does not directly define model throughput. It defines the communication work that the runtime must hide or distribute.

The DGX Spark 200 Gb/s rating describes its topology. It does not describe one socket or one RDMA interface.

Applications must use both PCI host paths to approach the full bandwidth.

#### Explanation

This notebook measured the RDMA topology and baseline performance of DGX Spark. The tests used host-memory RoCE traffic between two systems.

The local system exposes four RDMA devices. Two devices are active and use Ethernet with RoCE v2:

- `roceP2p1s0f1` uses the `10.200.0.0/30` network.
- `rocep1s0f1` uses the `10.201.0.0/30` network.

The two active interfaces use separate PCI domains. They do not represent two independent 200 Gb/s NICs.

DGX Spark exposes one ConnectX-7 through two PCI host paths. Together, these paths provide the advertised 200 Gb/s NIC capacity.

An RC ping-pong test first confirmed RDMA communication through the configured RoCE routes.

The latency tests used 8-byte RDMA writes. The two PCI paths gave different results:

- The `10.200` path averaged approximately 1.8 µs.
- The `10.201` path averaged approximately 1.4 µs.

Repeated paired trials showed a consistent difference. CPU placement also changed the measured latency.

Cortex-X925 cores gave lower latency than Cortex-A725 cores. A change of CPU cluster without a change of core type had little effect.

Tests with different client and server CPUs showed effects from the benchmark and path. The initiating CPU had more effect on `10.200`.

On `10.201`, a change to either endpoint CPU affected the result. This does not mean that the remote CPU processes each RDMA write.

The complete `ib_write_lat` test includes synchronization and completion work. This work makes the result sensitive to CPU placement at each endpoint.

The message-size sweep showed a change from message-rate limits to bandwidth limits:

- Small messages gave low byte throughput.
- Throughput increased quickly through the kilobyte range.
- Messages from 16 KiB through 64 KiB approached the single-path plateau.
- Large messages reached approximately 109–112 Gb/s on each path.

More queue pairs did not materially increase this limit. Separate processes on different Cortex-X925 cores also did not increase one-path throughput.

Thus, one queue pair, one posting loop, and one CPU core did not cause the one-path limit.

Concurrent use of both PCI paths gave these results:

- `10.200` delivered approximately 98 Gb/s.
- `10.201` delivered approximately 98 Gb/s.
- Total throughput reached approximately 196 Gb/s.

The total is approximately 98% of the advertised 200 Gb/s ConnectX-7 capacity.

The approximately 110 Gb/s one-path plateau is a PCI host-path limit. Applications must use both paths to reach almost all NIC bandwidth.

The tests support these conclusions:

1. DGX Spark provides RoCE v2 through two active RDMA interfaces.
2. The two PCI host paths have different small-message latency.
3. Cortex-X925 placement gives lower latency than Cortex-A725 placement.
4. One PCI path supports approximately 110 Gb/s of large-message RDMA writes.
5. More queue pairs or posting processes do not remove the one-path limit.
6. Concurrent use of both paths gives approximately 196 Gb/s in total.

#### Further Exploration

This notebook measured RDMA latency and bandwidth with host memory. The following tests can answer the remaining questions.

### Reverse-direction measurements

All controlled tests used `spark-0240` as the initiator and `spark-f868` as the target.

Reverse the roles to test whether the latency difference and bandwidth limits are the same in both directions.

### Bidirectional traffic

Use `ib_write_bw --bidirectional` or equivalent paired tests to measure simultaneous traffic in both directions.

These tests can show shared PCI, memory, or NIC resources. They can also test whether each direction provides 200 Gb/s.

### Automatic dual-path traffic

The dual-path experiment started one process for each interface. Test whether common communication libraries can use both paths automatically.

Candidates include these libraries:

- UCX
- NCCL
- MPI implementations with UCX support
- libfabric
- Distributed PyTorch communication backends

Test whether one logical collective can approach 196 Gb/s without application-managed traffic division.

### RDMA operation types

Compare these additional operations:

- RDMA read latency and bandwidth
- Send and receive operations
- Atomic operations
- Different completion and queue-depth settings

These operations use different NIC and endpoint functions. They can show other CPU or PCI-path effects.

### Queue depth and completion moderation

More queue pairs did not increase single-path bandwidth. Other `perftest` settings can still affect performance:

- Transmit depth
- Number of outstanding requests
- Inline-data thresholds
- Completion-queue moderation
- Event completions compared with polling

These tests can identify the cause of the small increase from one to two queue pairs.

### CPU use and power

The benchmarks measured transfer performance but not its CPU cost.

Measure core use, cycles, instructions, and power. Compare RDMA offload with the cost of benchmark polling.

### GPUDirect RDMA

The current tests used host memory. Distributed accelerator workloads need direct transfers between GPU-accessible memory and the NIC.

Answer these questions:

- Does DGX Spark support and enable GPUDirect RDMA?
- Can the system register unified-memory buffers directly?
- Do transfers avoid intermediate CPU copies?
- How do GPU-memory latency and bandwidth compare with host-memory results?
- Can GPU traffic use both PCI host paths at the same time?

### End-to-end collective performance

Microbenchmarks isolate the transport. LLM systems use all-reduce, all-gather, reduce-scatter, and all-to-all collectives.

Measure these operations across two DGX Spark systems:

1. Run an NCCL point-to-point transfer.
2. Run an NCCL all-reduce operation.
3. Run a tensor-parallel matrix multiplication.
4. Run a pipeline-parallel activation transfer.
5. Run a mixture-of-experts all-to-all operation.

These tests show how much of the 196 Gb/s dual-path result an LLM runtime can use.

#### Observations

Run the cells on one DGX Spark. Keep all output before you make conclusions.

Answer these questions first:

1. Which RDMA tools are installed?
2. Which RDMA devices are visible?
3. Which kernel driver and PCI device support each RDMA device?
4. Which Linux network interfaces map to the RDMA devices?
5. Which link layer does each RDMA port use?
6. Which ports are active, and which nominal rate does each port report?
7. Are the related network interfaces active and assigned an IP address?
8. Does the routing table contain routes through these interfaces?

This inventory alone does not support conclusions about bandwidth, latency, CPU use, or GPUDirect RDMA.

### Classification used in the synthesis

Candidate statements will be classified as:

1. **Measured** — directly visible in a saved output from the originating notebook.
2. **Derived** — calculated from saved measurements using an explicit transformation.
3. **Architectural inference** — an explanation based on observed behavior and system structure, but not directly measured.
4. **Unresolved** — suggested by the experiment but not established by the saved outputs.

Execution coverage and TODO counts are retained as provenance metadata. They are not themselves performance findings.

### Evidence ledger

The narrative sections identify candidate conclusions, but the final synthesis requires a smaller set of traceable claims.

Each ledger entry records:

- the originating notebook;
- the subsystem or performance layer;
- the claim being considered;
- whether it is measured, derived, inferred, or unresolved;
- the saved output or transformation that supports it;
- its relevance to later LLM experiments.

The ledger is intentionally selective. It captures the findings with the greatest cross-layer explanatory value rather than reproducing every benchmark result.

In [16]:
def validate_evidence_ledger(
    ledger: pd.DataFrame,
    candidate_notebooks: list[str],
) -> None:
    missing_columns = [
        column for column in evidence_columns if column not in ledger.columns
    ]
    if missing_columns:
        raise ValueError(f"Missing evidence columns: {missing_columns}")

    unknown_notebooks = sorted(
        set(ledger["notebook"].dropna()) - set(candidate_notebooks)
    )
    if unknown_notebooks:
        raise ValueError(
            f"Evidence refers to non-candidate notebooks: {unknown_notebooks}"
        )

    unknown_classifications = sorted(
        set(ledger["classification"].dropna()) - allowed_classifications
    )
    if unknown_classifications:
        raise ValueError(f"Unknown evidence classifications: {unknown_classifications}")

    duplicated_claims = ledger.duplicated(
        subset=["notebook", "claim"],
        keep=False,
    )
    if duplicated_claims.any():
        duplicates = ledger.loc[
            duplicated_claims,
            ["notebook", "claim"],
        ]
        raise ValueError(
            f"Duplicate evidence claims:\n{duplicates.to_string(index=False)}"
        )

In [17]:
evidence_columns = [
    "notebook",
    "layer",
    "claim",
    "classification",
    "support",
    "llm_relevance",
]

allowed_classifications = {
    "measured",
    "derived",
    "architectural inference",
    "unresolved",
}

evidence_ledger = pd.DataFrame(
    [
        {
            "notebook": "00-machine-overview.ipynb",
            "layer": "machine topology",
            "claim": (
                "The recorded system has 20 online ARM CPU cores, "
                "split into ten Cortex-X925 and ten Cortex-A725 cores, "
                "with one hardware thread per core."
            ),
            "classification": "measured",
            "support": (
                "`lscpu` reports 20 online CPUs, one thread per core, "
                "ten Cortex-X925 cores, and ten Cortex-A725 cores."
            ),
            "llm_relevance": (
                "CPU-side tokenization, request handling, sampling, and "
                "data preparation may run on two materially different "
                "core classes."
            ),
        },
        {
            "notebook": "00-machine-overview.ipynb",
            "layer": "memory topology",
            "claim": (
                "Linux exposes one NUMA node containing all 20 CPU cores "
                "and approximately 121 GiB of total memory."
            ),
            "classification": "measured",
            "support": (
                "`numactl --hardware` reports one NUMA node with CPUs "
                "0-19 and 124,609 MB; `free -h` reports 121 GiB total."
            ),
            "llm_relevance": (
                "Model weights, KV cache, CPU allocations, and GPU-visible "
                "unified-memory pressure ultimately share one system-level "
                "memory capacity."
            ),
        },
        {
            "notebook": "00-machine-overview.ipynb",
            "layer": "accelerator",
            "claim": (
                "The recorded accelerator is one NVIDIA GB10 using driver "
                "580.159.03 with CUDA 13.0 support."
            ),
            "classification": "measured",
            "support": (
                "`nvidia-smi` identifies NVIDIA GB10, driver 580.159.03, "
                "and CUDA version 13.0."
            ),
            "llm_relevance": (
                "This establishes the accelerator and software baseline "
                "under which the later CUDA and GPU-memory measurements "
                "were collected."
            ),
        },
        {
            "notebook": "00-machine-overview.ipynb",
            "layer": "unified memory reporting",
            "claim": (
                "`nvidia-smi` does not expose a conventional dedicated-GPU "
                "memory-usage counter on this GB10 system."
            ),
            "classification": "measured",
            "support": (
                "The saved `nvidia-smi` output reports `Not Supported` "
                "for memory usage."
            ),
            "llm_relevance": (
                "GPU memory capacity and pressure cannot be inferred from "
                "the usual discrete-GPU `nvidia-smi` memory field and need "
                "process- or framework-level measurement."
            ),
        },
        {
            "notebook": "01-cpu-architecture.ipynb",
            "layer": "CPU instruction support",
            "claim": (
                "The displayed records for logical CPUs 0 and 1 report "
                "SVE, SVE2, BF16, and 8-bit matrix instruction support."
            ),
            "classification": "measured",
            "support": (
                "The saved `/proc/cpuinfo` excerpt contains matching "
                "feature lists for complete records of CPUs 0 and 1."
            ),
            "llm_relevance": (
                "Compatible CPU kernels may use these instruction classes "
                "for preprocessing or inference, although this notebook "
                "does not measure their performance."
            ),
        },
        {
            "notebook": "01-cpu-architecture.ipynb",
            "layer": "CPU heterogeneity",
            "claim": (
                "The current CPU-architecture experiment does not establish "
                "a performance difference between core classes."
            ),
            "classification": "unresolved",
            "support": (
                "The run prints only a truncated `/proc/cpuinfo` excerpt; "
                "it sets no affinity and records no workload timings."
            ),
            "llm_relevance": (
                "Any claim about placing latency-sensitive LLM host work "
                "on Cortex-X925 rather than Cortex-A725 cores requires a "
                "separate affinity-controlled benchmark."
            ),
        },
    ],
    columns=evidence_columns,
)

In [18]:
validate_evidence_ledger(
    evidence_ledger,
    candidate_notebooks,
)

print(f"Validated {len(evidence_ledger)} evidence entries.")

evidence_ledger

Validated 6 evidence entries.

,notebook,layer,claim,classification,support,llm_relevance
0,00-machine-overview.ipynb,machine topology,The recorded system has 20 online ARM CPU core...,measured,"`lscpu` reports 20 online CPUs, one thread per...","CPU-side tokenization, request handling, sampl..."
1,00-machine-overview.ipynb,memory topology,Linux exposes one NUMA node containing all 20 ...,measured,`numactl --hardware` reports one NUMA node wit...,"Model weights, KV cache, CPU allocations, and ..."
2,00-machine-overview.ipynb,accelerator,The recorded accelerator is one NVIDIA GB10 us...,measured,"`nvidia-smi` identifies NVIDIA GB10, driver 58...",This establishes the accelerator and software ...
3,00-machine-overview.ipynb,unified memory reporting,`nvidia-smi` does not expose a conventional de...,measured,The saved `nvidia-smi` output reports `Not Sup...,GPU memory capacity and pressure cannot be inf...
4,01-cpu-architecture.ipynb,CPU instruction support,The displayed records for logical CPUs 0 and 1...,measured,The saved `/proc/cpuinfo` excerpt contains mat...,Compatible CPU kernels may use these instructi...
5,01-cpu-architecture.ipynb,CPU heterogeneity,The current CPU-architecture experiment does n...,unresolved,The run prints only a truncated `/proc/cpuinfo...,Any claim about placing latency-sensitive LLM ...

### Initial evidence interpretation

The first two notebooks establish different kinds of evidence.

`00-machine-overview.ipynb` provides a measured platform baseline: heterogeneous CPU core groups, one NUMA domain, Linux-visible memory capacity, and the NVIDIA GB10 software environment.

`01-cpu-architecture.ipynb` is more limited. It confirms instruction features for the displayed logical CPUs, but it does not perform the affinity-controlled timing experiment needed to quantify heterogeneous-core performance. Core-placement effects therefore remain unresolved in the current repository record.

In [20]:
memory_evidence = pd.DataFrame(
    [
        {
            "notebook": "02-memory-hierarchy.ipynb",
            "layer": "CPU cache topology",
            "claim": (
                "The representative CPUs have 64 KiB private L1 data "
                "caches and 2 MiB private L2 caches, but belong to "
                "different shared-L3 domains: 8 MiB for CPUs 0-9 and "
                "16 MiB for CPUs 10-19."
            ),
            "classification": "measured",
            "support": (
                "The sysfs cache inventory reports CPU 5 with an "
                "8 MiB L3 shared by CPUs 0-9 and CPU 15 with a "
                "16 MiB L3 shared by CPUs 10-19."
            ),
            "llm_relevance": (
                "CPU-side working sets such as tokenizer tables, request "
                "metadata, and preprocessing buffers can experience "
                "different cache capacity depending on core placement."
            ),
        },
        {
            "notebook": "02-memory-hierarchy.ipynb",
            "layer": "memory latency",
            "claim": (
                "Dependent random-load latency increased from about "
                "1.3 ns for small cache-resident working sets to about "
                "4 ns in the L2 region, about 6 ns in shared cache, and "
                "tens to roughly 100 ns for large working sets."
            ),
            "classification": "measured",
            "support": (
                "The pointer-chasing benchmark reports distinct latency "
                "regimes as working-set size crosses private cache, "
                "shared cache, and main-memory scales."
            ),
            "llm_relevance": (
                "Latency-sensitive pointer-heavy host work cannot be "
                "reasoned about from arithmetic throughput alone; "
                "working-set size and locality materially affect it."
            ),
        },
        {
            "notebook": "02-memory-hierarchy.ipynb",
            "layer": "CPU memory bandwidth",
            "claim": (
                "A vectorized sequential read reached about 124-125 GB/s "
                "for cache-resident arrays but only about 32-35 GB/s for "
                "a 256 MiB DRAM-resident working set."
            ),
            "classification": "measured",
            "support": (
                "The eight-accumulator loop was vectorized with 128-bit "
                "vectors; recorded bandwidth remained near 124-125 GB/s "
                "for small working sets and fell to 32-35 GB/s at "
                "256 MiB."
            ),
            "llm_relevance": (
                "CPU kernels can be compute- or cache-throughput-bound "
                "for small data but become constrained by sustainable "
                "memory bandwidth once their working set reaches DRAM."
            ),
        },
        {
            "notebook": "02-memory-hierarchy.ipynb",
            "layer": "CPU optimization",
            "claim": (
                "Removing a single reduction dependency and enabling "
                "vectorization increased cache-resident sequential-read "
                "throughput from about 31 GB/s to about 124-125 GB/s."
            ),
            "classification": "derived",
            "support": (
                "The recorded scalar result is approximately 31 GB/s "
                "and the vectorized eight-accumulator result is "
                "approximately 124-125 GB/s, implying roughly a "
                "fourfold increase for cache-resident data."
            ),
            "llm_relevance": (
                "Instruction-level parallelism and vectorization can "
                "matter as much as core frequency for CPU-side kernels "
                "that have sufficient locality."
            ),
        },
        {
            "notebook": "03-linux-memory.ipynb",
            "layer": "virtual memory",
            "claim": (
                "Reserving a 1 GiB anonymous mapping increased process "
                "virtual size by exactly 1024 MiB while increasing RSS "
                "by only 0.19 MiB."
            ),
            "classification": "measured",
            "support": (
                "`VmSize` rose from 2634.42 MiB to 3658.42 MiB, while "
                "`RssAnon` and smaps anonymous memory did not increase."
            ),
            "llm_relevance": (
                "A large virtual allocation or reservation does not by "
                "itself imply that model or KV-cache pages consume the "
                "same amount of physical memory."
            ),
        },
        {
            "notebook": "03-linux-memory.ipynb",
            "layer": "demand paging",
            "claim": (
                "Touching one byte in every 4 KiB page of the reserved "
                "1 GiB mapping caused RSS to increase by 1024.19 MiB and "
                "anonymous RSS by exactly 1024 MiB."
            ),
            "classification": "measured",
            "support": (
                "Each additional 128 MiB of pages touched produced an "
                "approximately 128 MiB increase in RSS and anonymous RSS."
            ),
            "llm_relevance": (
                "Physical memory pressure appears when pages are first "
                "accessed, so allocation timing and first-touch behavior "
                "can affect model-loading latency and observed memory use."
            ),
        },
        {
            "notebook": "03-linux-memory.ipynb",
            "layer": "page tables",
            "claim": (
                "Making the 1 GiB mapping resident increased the "
                "system page-table counter by approximately 2.1 MiB."
            ),
            "classification": "measured",
            "support": (
                "The recorded system PageTables counter increased by "
                "about 2.1 MiB while 262,144 individual 4 KiB pages "
                "were resident."
            ),
            "llm_relevance": (
                "Large numbers of small mappings or pages create memory-"
                "management overhead in addition to the payload data."
            ),
        },
        {
            "notebook": "03-linux-memory.ipynb",
            "layer": "page tables",
            "claim": (
                "The observed approximately 2.1 MiB page-table increase "
                "is consistent with roughly 2 MiB of leaf page-table "
                "entries for 262,144 mapped 4 KiB pages."
            ),
            "classification": "architectural inference",
            "support": (
                "262,144 pages multiplied by an 8-byte page-table entry "
                "equals 2 MiB; the measured counter rose by about "
                "2.1 MiB."
            ),
            "llm_relevance": (
                "The page granularity used for large model mappings can "
                "influence translation structures and memory-management "
                "overhead."
            ),
        },
    ],
    columns=evidence_columns,
)

evidence_ledger = pd.concat(
    [
        evidence_ledger,
        memory_evidence,
    ],
    ignore_index=True,
)

validate_evidence_ledger(
    evidence_ledger,
    candidate_notebooks,
)

evidence_ledger

,notebook,layer,claim,classification,support,llm_relevance
0,00-machine-overview.ipynb,machine topology,The recorded system has 20 online ARM CPU core...,measured,"`lscpu` reports 20 online CPUs, one thread per...","CPU-side tokenization, request handling, sampl..."
1,00-machine-overview.ipynb,memory topology,Linux exposes one NUMA node containing all 20 ...,measured,`numactl --hardware` reports one NUMA node wit...,"Model weights, KV cache, CPU allocations, and ..."
2,00-machine-overview.ipynb,accelerator,The recorded accelerator is one NVIDIA GB10 us...,measured,"`nvidia-smi` identifies NVIDIA GB10, driver 58...",This establishes the accelerator and software ...
3,00-machine-overview.ipynb,unified memory reporting,`nvidia-smi` does not expose a conventional de...,measured,The saved `nvidia-smi` output reports `Not Sup...,GPU memory capacity and pressure cannot be inf...
4,01-cpu-architecture.ipynb,CPU instruction support,The displayed records for logical CPUs 0 and 1...,measured,The saved `/proc/cpuinfo` excerpt contains mat...,Compatible CPU kernels may use these instructi...
5,01-cpu-architecture.ipynb,CPU heterogeneity,The current CPU-architecture experiment does n...,unresolved,The run prints only a truncated `/proc/cpuinfo...,Any claim about placing latency-sensitive LLM ...
6,02-memory-hierarchy.ipynb,CPU cache topology,The representative CPUs have 64 KiB private L1...,measured,The sysfs cache inventory reports CPU 5 with a...,CPU-side working sets such as tokenizer tables...
7,02-memory-hierarchy.ipynb,memory latency,Dependent random-load latency increased from a...,measured,The pointer-chasing benchmark reports distinct...,Latency-sensitive pointer-heavy host work cann...
8,02-memory-hierarchy.ipynb,CPU memory bandwidth,A vectorized sequential read reached about 124...,measured,The eight-accumulator loop was vectorized with...,CPU kernels can be compute- or cache-throughpu...
9,02-memory-hierarchy.ipynb,CPU optimization,Removing a single reduction dependency and ena...,derived,The recorded scalar result is approximately 31...,Instruction-level parallelism and vectorizatio...
10,03-linux-memory.ipynb,virtual memory,Reserving a 1 GiB anonymous mapping increased ...,measured,"`VmSize` rose from 2634.42 MiB to 3658.42 MiB,...",A large virtual allocation or reservation does...
11,03-linux-memory.ipynb,demand paging,Touching one byte in every 4 KiB page of the r...,measured,Each additional 128 MiB of pages touched produ...,Physical memory pressure appears when pages ar...
12,03-linux-memory.ipynb,page tables,Making the 1 GiB mapping resident increased th...,measured,The recorded system PageTables counter increas...,Large numbers of small mappings or pages creat...
13,03-linux-memory.ipynb,page tables,The observed approximately 2.1 MiB page-table ...,architectural inference,"262,144 pages multiplied by an 8-byte page-tab...",The page granularity used for large model mapp...

### Memory-layer interpretation

The CPU memory results show that “CPU performance” is not one quantity. Dependent access latency, sequential bandwidth, cache capacity, instruction-level parallelism, and vectorization expose different limits.

The Linux memory experiment adds a second distinction: virtual address-space size, resident physical memory, and system-wide available memory are related but not interchangeable. A one-GiB mapping consumed almost no physical memory until its pages were touched.

Together, these results imply that later LLM experiments must report both access behavior and allocation state. A model can have a large virtual footprint without all pages being resident, while a resident workload can still behave very differently depending on whether its active working set is served from cache or DRAM.

In [22]:
compute_evidence = pd.DataFrame(
    [
        {
            "notebook": "04-vectorization.ipynb",
            "layer": "Python overhead",
            "claim": (
                "For a 16-element multiply-add, the Python loop was "
                "faster than NumPy because NumPy's fixed dispatch cost "
                "exceeded the short loop's execution cost."
            ),
            "classification": "measured",
            "support": (
                "The size sweep records Python ahead at 16 elements; "
                "NumPy overtakes it by 64 elements."
            ),
            "llm_relevance": (
                "Moving tiny host operations into an array library or "
                "accelerator kernel is not automatically beneficial when "
                "dispatch overhead exceeds useful work."
            ),
        },
        {
            "notebook": "04-vectorization.ipynb",
            "layer": "interpreter overhead",
            "claim": (
                "For larger arrays, NumPy exceeded the Python loop by "
                "more than 100 times."
            ),
            "classification": "measured",
            "support": (
                "The recorded Python implementation required about "
                "23-40 ns per element, while NumPy reached approximately "
                "0.18-0.34 ns per element for larger inputs."
            ),
            "llm_relevance": (
                "Per-element Python work is unsuitable for throughput-"
                "sensitive preprocessing and tensor manipulation; loops "
                "should be moved into compiled or fused kernels."
            ),
        },
        {
            "notebook": "04-vectorization.ipynb",
            "layer": "SIMD",
            "claim": (
                "The largest measured SIMD speedup over the compiled "
                "scalar kernel was 1.86 times at 262,144 elements."
            ),
            "classification": "derived",
            "support": (
                "The scalar kernel took 70.90 microseconds and the "
                "vectorized kernel took 38.19 microseconds."
            ),
            "llm_relevance": (
                "SIMD can materially accelerate cache-resident CPU kernels "
                "used in tokenization, quantization, sampling, or data "
                "format conversion."
            ),
        },
        {
            "notebook": "04-vectorization.ipynb",
            "layer": "memory bandwidth",
            "claim": (
                "The SIMD advantage declined to only 1.05 times for the "
                "128 MiB working set."
            ),
            "classification": "derived",
            "support": (
                "At the largest tested size, scalar and vectorized kernels "
                "both processed approximately 3.2-3.4 billion elements "
                "per second."
            ),
            "llm_relevance": (
                "Once a CPU kernel is bandwidth-bound, wider vector "
                "execution provides little benefit unless data movement "
                "is reduced."
            ),
        },
        {
            "notebook": "04-vectorization.ipynb",
            "layer": "kernel fusion",
            "claim": (
                "A fused compiled multiply-add can outperform separate "
                "NumPy expressions by completing the operation in one "
                "memory traversal."
            ),
            "classification": "architectural inference",
            "support": (
                "The notebook observes that separate NumPy ufuncs may "
                "require multiple passes and temporary-array management, "
                "while the compiled kernel fuses the operations."
            ),
            "llm_relevance": (
                "Fusion is valuable in LLM runtimes because avoiding "
                "intermediate tensors reduces memory traffic and launch "
                "overhead."
            ),
        },
        {
            "notebook": "05-cuda-fundamentals.ipynb",
            "layer": "CUDA timing",
            "claim": (
                "The Python enqueue duration for a 64 MiB CUDA "
                "multiply-add was much shorter than the synchronized "
                "host duration."
            ),
            "classification": "measured",
            "support": (
                "Across 100 runs, mean enqueue time was approximately "
                "9.86 microseconds while mean synchronized time was "
                "approximately 1247.91 microseconds."
            ),
            "llm_relevance": (
                "Unsynchronized Python timing substantially understates "
                "completed GPU work and cannot be used directly as kernel "
                "or inference latency."
            ),
        },
        {
            "notebook": "05-cuda-fundamentals.ipynb",
            "layer": "CUDA cold start",
            "claim": (
                "The first CUDA multiplication in a fresh subprocess was "
                "approximately 10.3-10.6 times slower than its warmed-up "
                "multiplication."
            ),
            "classification": "measured",
            "support": (
                "The subprocess repetitions consistently recorded a "
                "roughly tenfold first-use slowdown."
            ),
            "llm_relevance": (
                "Model-serving latency should be measured after explicit "
                "runtime, allocator, and kernel warm-up, while cold-start "
                "latency should be reported separately."
            ),
        },
        {
            "notebook": "05-cuda-fundamentals.ipynb",
            "layer": "CUDA Graph submission",
            "claim": (
                "For a fixed sequence of 64 small additions, CUDA Graph "
                "replay reduced host enqueue time from 196.937 "
                "microseconds to approximately 2 microseconds."
            ),
            "classification": "measured",
            "support": (
                "Graph replay enqueue remained about 1.98-2.06 "
                "microseconds, producing a 98.47-times host-submission "
                "speedup at 64 operations."
            ),
            "llm_relevance": (
                "Autoregressive decoding repeatedly submits many short "
                "kernels, so graph replay can reduce CPU launch overhead "
                "when shapes and memory addresses are stable."
            ),
        },
        {
            "notebook": "05-cuda-fundamentals.ipynb",
            "layer": "CUDA Graph execution",
            "claim": (
                "For the 64-operation sequence, CUDA Graph replay reduced "
                "completed CUDA-event time from 247.792 microseconds to "
                "121.440 microseconds."
            ),
            "classification": "measured",
            "support": (
                "The recorded event timings imply approximately a "
                "2.04-times reduction in completed sequence duration."
            ),
            "llm_relevance": (
                "Graph replay can reduce not only Python submission cost "
                "but also inter-kernel gaps that contribute directly to "
                "token latency."
            ),
        },
        {
            "notebook": "05-cuda-fundamentals.ipynb",
            "layer": "CUDA Graph applicability",
            "claim": (
                "CUDA Graph benefits require stable operation topology, "
                "tensor shapes, and compatible memory addresses."
            ),
            "classification": "architectural inference",
            "support": (
                "Graph capture replays a previously recorded fixed "
                "sequence rather than reconstructing arbitrary Python "
                "control flow."
            ),
            "llm_relevance": (
                "Graph capture is most applicable to stable decode buckets "
                "and less applicable when batches, shapes, or control flow "
                "change on every request."
            ),
        },
    ],
    columns=evidence_columns,
)

evidence_ledger = pd.concat(
    [
        evidence_ledger,
        compute_evidence,
    ],
    ignore_index=True,
)

validate_evidence_ledger(
    evidence_ledger,
    candidate_notebooks,
)

evidence_ledger

,notebook,layer,claim,classification,support,llm_relevance
0,00-machine-overview.ipynb,machine topology,The recorded system has 20 online ARM CPU core...,measured,"`lscpu` reports 20 online CPUs, one thread per...","CPU-side tokenization, request handling, sampl..."
1,00-machine-overview.ipynb,memory topology,Linux exposes one NUMA node containing all 20 ...,measured,`numactl --hardware` reports one NUMA node wit...,"Model weights, KV cache, CPU allocations, and ..."
2,00-machine-overview.ipynb,accelerator,The recorded accelerator is one NVIDIA GB10 us...,measured,"`nvidia-smi` identifies NVIDIA GB10, driver 58...",This establishes the accelerator and software ...
3,00-machine-overview.ipynb,unified memory reporting,`nvidia-smi` does not expose a conventional de...,measured,The saved `nvidia-smi` output reports `Not Sup...,GPU memory capacity and pressure cannot be inf...
4,01-cpu-architecture.ipynb,CPU instruction support,The displayed records for logical CPUs 0 and 1...,measured,The saved `/proc/cpuinfo` excerpt contains mat...,Compatible CPU kernels may use these instructi...
5,01-cpu-architecture.ipynb,CPU heterogeneity,The current CPU-architecture experiment does n...,unresolved,The run prints only a truncated `/proc/cpuinfo...,Any claim about placing latency-sensitive LLM ...
6,02-memory-hierarchy.ipynb,CPU cache topology,The representative CPUs have 64 KiB private L1...,measured,The sysfs cache inventory reports CPU 5 with a...,CPU-side working sets such as tokenizer tables...
7,02-memory-hierarchy.ipynb,memory latency,Dependent random-load latency increased from a...,measured,The pointer-chasing benchmark reports distinct...,Latency-sensitive pointer-heavy host work cann...
8,02-memory-hierarchy.ipynb,CPU memory bandwidth,A vectorized sequential read reached about 124...,measured,The eight-accumulator loop was vectorized with...,CPU kernels can be compute- or cache-throughpu...
9,02-memory-hierarchy.ipynb,CPU optimization,Removing a single reduction dependency and ena...,derived,The recorded scalar result is approximately 31...,Instruction-level parallelism and vectorizatio...
10,03-linux-memory.ipynb,virtual memory,Reserving a 1 GiB anonymous mapping increased ...,measured,"`VmSize` rose from 2634.42 MiB to 3658.42 MiB,...",A large virtual allocation or reservation does...
11,03-linux-memory.ipynb,demand paging,Touching one byte in every 4 KiB page of the r...,measured,Each additional 128 MiB of pages touched produ...,Physical memory pressure appears when pages ar...
12,03-linux-memory.ipynb,page tables,Making the 1 GiB mapping resident increased th...,measured,The recorded system PageTables counter increas...,Large numbers of small mappings or pages creat...
13,03-linux-memory.ipynb,page tables,The observed approximately 2.1 MiB page-table ...,architectural inference,"262,144 pages multiplied by an 8-byte page-tab...",The page granularity used for large model mapp...
14,04-vectorization.ipynb,Python overhead,"For a 16-element multiply-add, the Python loop...",measured,The size sweep records Python ahead at 16 elem...,Moving tiny host operations into an array libr...
15,04-vectorization.ipynb,interpreter overhead,"For larger arrays, NumPy exceeded the Python l...",measured,The recorded Python implementation required ab...,Per-element Python work is unsuitable for thro...
16,04-vectorization.ipynb,SIMD,The largest measured SIMD speedup over the com...,derived,The scalar kernel took 70.90 microseconds and ...,SIMD can materially accelerate cache-resident ...
17,04-vectorization.ipynb,memory bandwidth,The SIMD advantage declined to only 1.05 times...,derived,"At the largest tested size, scalar and vectori...","Once a CPU kernel is bandwidth-bound, wider ve..."
18,04-vectorization.ipynb,kernel fusion,A fused compiled multiply-add can outperform s...,architectural inference,The notebook observes that separate NumPy ufun...,Fusion is valuable in LLM runtimes because avo...
19,05-cuda-fundamentals.ipynb,CUDA timing,The Python enqueue duration for a 64 MiB CUDA ...,measured,"Across 100 runs, mean enqueue time was approxi...",Unsynchronized Python timing substantially und...
20,05-cuda-fundamentals.ipynb,CUDA cold start,The first CUDA multiplication in a fresh subpr...,measured,The subprocess repetitions consistently record...,Model-serving latency should be measured after...
21,05-cuda-fundamentals.ipynb,CUDA Graph submission,"For a fixed sequence of 64 small additions, CU...",measured,Graph replay enqueue remained about 1.98-2.06 ...,Autoregressive decoding repeatedly submits man...
22,05-cuda-fundamentals.ipynb,CUDA Graph execution,"For the 64-operation sequence, CUDA Graph repl...",measured,The recorded event timings imply approximately...,Graph replay can reduce not only Python submis...
23,05-cuda-fundamentals.ipynb,CUDA Graph applicability,CUDA Graph benefits require stable operation t...,architectural inference,Graph capture replays a previously recorded fi...,Graph capture is most applicable to stable dec...

### Compute and submission interpretation

The vectorization and CUDA results expose the same scale-dependent pattern at two different layers.

For very small operations, fixed dispatch or launch overhead can exceed the useful computation. As work increases, moving execution into compiled, SIMD, or GPU kernels becomes highly advantageous. At still larger scales, the benefit can flatten when memory movement rather than arithmetic becomes dominant.

CUDA adds an asynchronous submission layer. A short Python call can represent only enqueue time, while the actual GPU work completes later. CUDA Graph replay demonstrates that repeated submission itself can become a bottleneck: bundling a stable sequence reduced host submission cost by almost two orders of magnitude and reduced completed execution time by about twofold for the longest tested sequence.

These results support treating LLM execution as a pipeline of distinct costs: Python or framework dispatch, kernel launch, device execution, synchronization, and memory traffic.

In [23]:
ledger_coverage = (
    evidence_ledger.groupby(
        [
            "notebook",
            "classification",
        ],
        observed=True,
    )
    .size()
    .rename("claims")
    .reset_index()
    .sort_values(
        [
            "notebook",
            "classification",
        ]
    )
    .reset_index(drop=True)
)

covered_notebooks = evidence_ledger["notebook"].nunique()

print(f"Evidence entries: {len(evidence_ledger)}")
print(f"Notebooks covered: {covered_notebooks} / {len(candidate_notebooks)}")

ledger_coverage

Evidence entries: 24
Notebooks covered: 6 / 10

                      notebook           classification  claims
0    00-machine-overview.ipynb                 measured       4
1    01-cpu-architecture.ipynb                 measured       1
2    01-cpu-architecture.ipynb               unresolved       1
3    02-memory-hierarchy.ipynb                  derived       1
4    02-memory-hierarchy.ipynb                 measured       3
5        03-linux-memory.ipynb  architectural inference       1
6        03-linux-memory.ipynb                 measured       3
7       04-vectorization.ipynb  architectural inference       1
8       04-vectorization.ipynb                  derived       2
9       04-vectorization.ipynb                 measured       2
10  05-cuda-fundamentals.ipynb  architectural inference       1
11  05-cuda-fundamentals.ipynb                 measured       4

## Observations

TODO: Summarize measured findings and link each statement to its originating run.

## Explanation

TODO: Build a cross-layer explanation and distinguish evidence from remaining hypotheses.

## Connection to LLMs

Use the verified constraints to motivate concrete experiments in distributed inference, training, and communication.

## Further Exploration

TODO: Rank follow-up experiments by expected learning value, cost, and dependency on unresolved questions.